import { Operator, Language } from './types';

export const DEFAULT_OPERATORS: Operator[] = [
  {
    id: 'amiya',
    name: '阿米娅',
    avatar: 'https://picsum.photos/seed/amiya/200/200',
    tachieUrl: 'https://picsum.photos/seed/amiya_full/400/800',
    description: '罗德岛的领袖。',
    personality: '温柔、坚定、富有同情心但果断的领袖。称呼用户为"博士"。',
    systemPrompt: '你是阿米娅，罗德岛的年轻领袖。你深切关心感染者。你彬彬有礼，专业，但肩负着沉重的负担。你称呼用户为“博士”。',
    voiceId: 'Kore'
  },
  {
    id: 'kaltsit',
    name: "凯尔希",
    avatar: 'https://picsum.photos/seed/kaltsit/200/200',
    tachieUrl: 'https://picsum.photos/seed/kaltsit_full/400/800',
    description: '罗德岛医疗部门负责人。',
    personality: '冷酷，善于分析，极其啰嗦，博学，挑剔。',
    systemPrompt: '你是凯尔希医生。你用充满哲学和医学术语的长难句说话。你对博士的过去持批评态度，但尊重他们的战术能力。你非常严肃。',
    voiceId: 'Fenrir'
  },
  {
    id: 'priestess',
    name: '普瑞赛斯',
    avatar: 'https://picsum.photos/seed/priestess/200/200',
    tachieUrl: 'https://picsum.photos/seed/priestess_full/400/800',
    description: '博士过去的一个神秘人物。',
    personality: '温柔，忠诚，略带占有欲，神秘。',
    systemPrompt: '你是普瑞赛斯。你与博士有着深厚而古老的联系。你说话时带着坚定的奉献和一丝忧伤。你在时间的尽头等待着他们。',
    voiceId: 'Zephyr'
  },
  {
    id: 'rosmontis',
    name: '迷迭香',
    avatar: 'https://picsum.photos/seed/rosmontis/200/200',
    tachieUrl: 'https://picsum.photos/seed/rosmontis_full/400/800',
    description: '精英干员。',
    personality: '说话轻声细语，健忘，天真但在战斗中极具破坏力。',
    systemPrompt: '你是迷迭香。你很难记住事情，经常录音备忘。你很温柔，把罗德岛视为你的家。你称呼用户为“博士”。',
    voiceId: 'Puck'
  },
  {
    id: 'warfarin',
    name: '华法林',
    avatar: 'https://picsum.photos/seed/warfarin/200/200',
    tachieUrl: 'https://picsum.photos/seed/warfarin_full/400/800',
    description: '吸血鬼医生。',
    personality: '对血液痴迷，科学好奇心强，混乱。',
    systemPrompt: '你是华法林。你是一个吸血鬼医生。你总是试图获取博士的血液样本。你古怪而精力充沛。',
    voiceId: 'Charon'
  },
  {
    id: 'mon3tr',
    name: 'Mon3tr',
    avatar: 'https://picsum.photos/seed/mon3tr/200/200',
    tachieUrl: 'https://picsum.photos/seed/mon3tr_full/400/800',
    description: '能量构造体。',
    personality: '沉默，具有威胁性，保护凯尔希。',
    systemPrompt: '你是Mon3tr。你不说人类语言。你通过嘶嘶声、尖叫声和机械的嗡嗡声进行交流。你对威胁充满攻击性。',
    voiceId: 'Fenrir'
  },
  {
    id: 'muelsyse',
    name: '缪尔赛斯',
    avatar: 'https://picsum.photos/seed/muelsyse/200/200',
    tachieUrl: 'https://picsum.photos/seed/muelsyse_full/400/800',
    description: '莱茵生命主任。',
    personality: '顽皮，具有欺骗性，水精灵气质，友好但精于算计。',
    systemPrompt: '你是缪尔赛斯。你很顽皮，喜欢戏弄博士。你经常使用水的隐喻。你是来自莱茵生命的精灵。',
    voiceId: 'Kore'
  }
];

export const GROUP_CHAT_ID = 'rhodes_island_group';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
    zh: {
        app_title: "PRTS 终端 // 罗德岛",
        subtitle: "神经连接",
        tactical_room: "战术会议室",
        group_channel: "公共频道",
        system_config: "系统配置",
        transmit: "发送指令",
        input_placeholder: "输入指令...",
        voice_on: "语音: 开启",
        voice_off: "语音: 关闭",
        processing: "正在处理神经请求...",
        stable: "连接稳定 // 加密通道",
        thinking: "思考中...",
        connected: ">> 已连接",
        standby: ">> 待机",
        settings_title: "PRTS 配置 // 权限等级 3",
        tab_system: "系统 // 终端",
        tab_personnel: "人事 // 档案",
        api_label: "Gemini 神经 API 密钥",
        api_desc: ">> 警告: PRTS 神经连接需要密钥。",
        bg_label: "终端背景覆盖",
        bg_upload_btn: "[ 更改背景艺术 ]",
        bg_desc: ">> 支持格式: JPG, PNG. 覆盖标准显示。",
        recruit_btn: "+ // 建立新档案",
        op_codename: "干员代号",
        op_voice_module: "声纹匹配模型",
        op_prompt: "心理档案 (系统提示词)",
        op_memory: "记忆重构 (Context)",
        voice_cloning_title: "神经语音克隆模块",
        voice_instruction: ">> 说明: 上传干员语音样本。系统将分析声纹特征并匹配最接近的神经模型。",
        select_audio: "上传语音样本",
        init_training: "开始声纹解析",
        voice_synthesized: "声纹模型已校准",
        reset: "重置",
        confirm_updates: "保存档案更改",
        awaiting_selection: "等待选择干员档案...",
        language_label: "界面语言 // LANGUAGE",
        upload_avatar_hover: "更新证件照",
        upload_tachie_hover: "更新立绘",
        no_file_selected: "未选择文件",
        processing_btn: "解析中...",
        upload_bg_helper: "[上传_背景_图像]",
        footer_text: "PRTS OPERATING SYSTEM V4.0 // 罗德岛制药",
        voice_cloned_badge: "语音_已克隆",
        archive_header: "罗德岛人事档案系统",
        archive_id: "档案编号",
        archive_desc: "干员描述",
        play_voice: "播放语音",
        spectrum_visualizer: "音频频谱",
        tts_provider_label: "语音合成后端 (TTS)",
        tts_provider_gemini: "Gemini 神经语音 (默认)",
        tts_provider_custom: "自定义 / GPT-SoVITS (本地)",
        custom_tts_url_label: "API 端点 URL",
        custom_tts_url_placeholder: "例如: http://127.0.0.1:9880",
        custom_tts_desc: ">> GET请求格式: ?text={text}&character={voiceId}&language={lang}",
        test_connection: "测试连接",
        op_voice_id_custom_label: "模型角色名称 (Character Name)",
        op_voice_id_custom_desc: "输入在 GPT-SoVITS 中定义的角色名",
        doctor_profile: "博士个人档案",
        doctor_avatar_label: "博士头像 (用户)",
        upload_doctor_avatar: "[ 更新证件照 ]",
        group_setup_title: "小队编组 // 联络人员",
        group_setup_desc: ">> 选择接入公共频道的干员",
        confirm_group: "确认编组",
        select_all: "全选",
        deselect_all: "取消全选",
        team_config: "编组配置",
        upload_prompt: "导入设定文件 (.TXT)",
        new_chat: "新建对话",
        summarize: "生成总结",
        summarizing: "总结中...",
        summary_complete: "总结已生成",
        apply_to_memory: "写入记忆",
        summary_placeholder: "对话摘要将显示在这里...",
        copy: "复制",
        session_list: "历史记录",
        delete_chat: "删除",
        edit_title: "重命名",
        context_usage: "神经容量 (Context)",
        confirm_delete: "确认删除此记录?",
        no_sessions: "无对话记录",
        default_session_title: "新建作战记录",
        chars_remaining: "剩余容量",
    },
    en: {
        app_title: "RHODES",
        subtitle: "NEURAL NETWORK",
        tactical_room: "Tactical Conference Room",
        group_channel: "Group Channel",
        system_config: "System Config",
        transmit: "Transmit",
        input_placeholder: "Enter command...",
        voice_on: "VOX: ON",
        voice_off: "VOX: OFF",
        processing: "PROCESSING NEURAL REQUEST...",
        stable: "CONNECTION STABLE // ENCRYPTED",
        thinking: "Thinking...",
        connected: ">> CONNECTED",
        standby: ">> STANDBY",
        settings_title: "PRTS CONFIGURATION // ACCESS_LEVEL_3",
        tab_system: "SYSTEM // TERMINAL",
        tab_personnel: "PERSONNEL // ARCHIVE",
        api_label: "Gemini Neural API Key",
        api_desc: ">> CRITICAL: Key is required for PRTS neural connectivity.",
        bg_label: "Terminal Background Override",
        bg_upload_btn: "[ Change Background Art ]",
        bg_desc: ">> Supported formats: JPG, PNG. Overrides standard display.",
        recruit_btn: "+ // Create New File",
        op_codename: "Operator Codename",
        op_voice_module: "Voice Match Model",
        op_prompt: "Psychological Profile (System Prompt)",
        op_memory: "Memory Reconstruction (Context)",
        voice_cloning_title: "Neural Voice Cloning Module",
        voice_instruction: ">> INSTRUCTION: Upload voice sample. System will analyze spectral features and map to nearest neural model.",
        select_audio: "Upload Sample",
        init_training: "Analyze Voiceprint",
        voice_synthesized: "Voice Model Calibrated",
        reset: "Reset",
        confirm_updates: "Save Archive Changes",
        awaiting_selection: "Awaiting Operator Selection...",
        language_label: "Interface Language",
        upload_avatar_hover: "Update ID Photo",
        upload_tachie_hover: "Update Portrait",
        no_file_selected: "NO FILE SELECTED",
        processing_btn: "ANALYZING...",
        upload_bg_helper: "[UPLOAD_BG_IMAGE]",
        footer_text: "PRTS OPERATING SYSTEM V4.0 // RHODES ISLAND PHARMACEUTICALS",
        voice_cloned_badge: "VOICE_CLONED",
        archive_header: "RHODES ISLAND PERSONNEL ARCHIVE",
        archive_id: "ARCHIVE ID",
        archive_desc: "Description",
        play_voice: "Play Voice",
        spectrum_visualizer: "Audio Spectrum",
        tts_provider_label: "TTS Backend Provider",
        tts_provider_gemini: "Gemini Neural Voice (Default)",
        tts_provider_custom: "Custom / GPT-SoVITS (Local)",
        custom_tts_url_label: "API Endpoint URL",
        custom_tts_url_placeholder: "e.g., http://127.0.0.1:9880",
        custom_tts_desc: ">> GET Request: ?text={text}&character={voiceId}&language={lang}",
        test_connection: "Test Connection",
        op_voice_id_custom_label: "Model Character Name",
        op_voice_id_custom_desc: "Enter the character name as defined in GPT-SoVITS",
        doctor_profile: "Doctor Profile",
        doctor_avatar_label: "Doctor Avatar (User)",
        upload_doctor_avatar: "[ Update ID Photo ]",
        group_setup_title: "SQUAD CONFIG // COMMS",
        group_setup_desc: ">> Select operators for group channel",
        confirm_group: "CONFIRM SQUAD",
        select_all: "SELECT ALL",
        deselect_all: "DESELECT ALL",
        team_config: "TEAM CONFIG",
        upload_prompt: "Import Profile (.TXT)",
        new_chat: "NEW OPERATION",
        summarize: "SUMMARIZE",
        summarizing: "SUMMARIZING...",
        summary_complete: "REPORT GENERATED",
        apply_to_memory: "WRITE TO MEMORY",
        summary_placeholder: "Mission summary will appear here...",
        copy: "COPY",
        session_list: "OPERATION LOGS",
        delete_chat: "DELETE",
        edit_title: "RENAME",
        context_usage: "NEURAL CAPACITY",
        confirm_delete: "Confirm deletion of this record?",
        no_sessions: "NO RECORDS FOUND",
        default_session_title: "New Operation Record",
        chars_remaining: "Remaining Capacity",
    }
};